'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { projects, navigation, recentActivity, platformModules } from '@/lib/game-lab'
import { ArrowUpRight, Bell, Blocks, ChartNoAxesCombined, ChevronDown, Clock3, FolderKanban, Gamepad2, Images, LayoutDashboard, Menu, Pencil, Play, Plus, Search, Send, Settings2, Sparkles, Trophy, Users, X, type LucideIcon } from 'lucide-react'

const icons: Record<string, LucideIcon> = { 'layout-dashboard': LayoutDashboard, 'folder-kanban': FolderKanban, blocks: Blocks, images: Images, sparkles: Sparkles, send: Send, users: Users, trophy: Trophy, 'chart-no-axes-combined': ChartNoAxesCombined, pencil: Pencil, plus: Plus, play: Play }

export default function Page() {
  const [active, setActive] = useState('Dashboard')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [search, setSearch] = useState('')
  const visibleProjects = projects.filter((project) => project.name.toLowerCase().includes(search.toLowerCase()))
  const selectNav = (label: string) => { setActive(label); setMobileOpen(false) }

  return (
    <main className="min-h-screen bg-background text-foreground">
      <aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r border-border bg-sidebar px-4 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center justify-between px-2"><Logo /><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X /></Button></div>
        <nav className="mt-10 flex flex-1 flex-col gap-7" aria-label="Main navigation">
          {navigation.map((group) => <div key={group.label} className="flex flex-col gap-2"><p className="px-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">{group.label}</p>{group.items.map((item) => { const Icon = icons[item.icon]; return <button key={item.label} onClick={() => selectNav(item.label)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition-colors ${active === item.label ? 'bg-sidebar-primary text-sidebar-primary-foreground shadow-sm' : 'text-sidebar-foreground hover:bg-sidebar-accent'}`}><Icon className="size-4" /><span className="flex-1">{item.label}</span>{item.badge && <span className="rounded-full bg-sidebar-accent px-2 py-0.5 text-[10px] text-muted-foreground">{item.badge}</span>}</button> })}</div>)}
        </nav>
        <div className="border-t border-sidebar-border pt-4"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm text-sidebar-foreground hover:bg-sidebar-accent"><Settings2 className="size-4" />Settings</button><div className="mt-4 flex items-center gap-3 rounded-lg bg-sidebar-accent/60 p-3"><div className="flex size-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">AS</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Alex Smith</p><p className="truncate text-xs text-muted-foreground">Creator account</p></div><ChevronDown className="size-4 text-muted-foreground" /></div></div>
      </aside>
      {mobileOpen && <button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation overlay" />}
      <div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu /></Button><span className="font-mono text-xs text-muted-foreground">{active === 'Dashboard' ? 'HOME / DASHBOARD' : `BUILD / ${active.toUpperCase()}`}</span></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-md border border-input bg-muted/30 px-3 py-1.5 sm:flex"><Search className="size-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects" className="w-32 bg-transparent text-sm outline-none placeholder:text-muted-foreground" aria-label="Search projects" /></div><Button variant="ghost" size="icon" aria-label="Notifications"><Bell className="size-4" /></Button><Button size="sm" className="hidden gap-2 sm:flex"><Plus className="size-4" />New project</Button></div></header>
        <div className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-12"><section className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-primary" />Your creative workspace</div><h1 className="max-w-xl text-balance text-3xl font-semibold tracking-tight md:text-5xl">Make something <span className="text-primary">playable.</span></h1><p className="mt-3 max-w-lg text-pretty leading-6 text-muted-foreground">Welcome back, Alex. Your next world is waiting to be built.</p></div><Button className="w-fit gap-2"><Plus className="size-4" />Create a project</Button></section>
          <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Your projects</h2><p className="mt-1 text-sm text-muted-foreground">Pick up where you left off.</p></div><button className="flex items-center gap-1 text-sm font-medium text-primary hover:underline">View all <ArrowUpRight className="size-4" /></button></div><div className="grid gap-4 md:grid-cols-3">{visibleProjects.map((project) => <ProjectCard key={project.id} project={project} />)}<button className="group flex min-h-52 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-border bg-card/40 text-center transition-colors hover:border-primary/50 hover:bg-card"><span className="flex size-10 items-center justify-center rounded-full border border-border bg-background group-hover:border-primary/50"><Plus className="size-5 text-muted-foreground group-hover:text-primary" /></span><span className="text-sm font-medium">Create new project</span><span className="text-xs text-muted-foreground">Start with a blank canvas</span></button></div></section>
          <section className="mt-12 grid gap-8 lg:grid-cols-[1fr_320px]"><div><div className="mb-5"><h2 className="text-lg font-semibold">The lab</h2><p className="mt-1 text-sm text-muted-foreground">A modular foundation for your game-making journey.</p></div><div className="grid gap-3 sm:grid-cols-2">{platformModules.map((module) => { const Icon = icons[module.icon]; return <div key={module.title} className="rounded-xl border border-border bg-card p-5 transition-colors hover:border-primary/40"><div className="flex items-start justify-between"><span className="flex size-9 items-center justify-center rounded-lg bg-muted"><Icon className="size-4 text-primary" /></span><span className={`text-[10px] font-medium uppercase tracking-wide ${module.status === 'Coming soon' ? 'text-muted-foreground' : 'text-primary'}`}>{module.status}</span></div><h3 className="mt-4 font-medium">{module.title}</h3><p className="mt-1 text-sm leading-5 text-muted-foreground">{module.description}</p></div> })}</div></div><div><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recent activity</h2><p className="mt-1 text-sm text-muted-foreground">Your latest moves.</p></div><Clock3 className="size-4 text-muted-foreground" /></div><div className="flex flex-col rounded-xl border border-border bg-card p-2">{recentActivity.map((item) => { const Icon = icons[item.icon]; return <div key={item.title + item.time} className="flex items-center gap-3 rounded-lg p-3"><span className="flex size-8 items-center justify-center rounded-md bg-muted"><Icon className="size-3.5 text-muted-foreground" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.detail}</p></div><time className="text-xs text-muted-foreground">{item.time}</time></div> })}</div><div className="mt-4 rounded-xl border border-border bg-primary p-5 text-primary-foreground"><Sparkles className="size-5" /><h3 className="mt-4 font-medium">Your ideas have a home.</h3><p className="mt-1 text-sm leading-5 text-primary-foreground/75">Alex Game Lab is being built for curious creators like you.</p></div></div></section>
        </div></div>
    </main>
  )
}

function Logo() { return <div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Gamepad2 className="size-4" /></span><span className="font-semibold tracking-tight">Alex Game <span className="text-primary">Lab</span></span></div> }
function ProjectCard({ project }: { project: (typeof projects)[number] }) { return <article className="overflow-hidden rounded-xl border border-border bg-card transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg"><div className={`h-28 bg-${project.color} relative p-4`}><div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'linear-gradient(135deg, transparent 25%, currentColor 25%, currentColor 50%, transparent 50%, transparent 75%, currentColor 75%)', backgroundSize: '18px 18px' }} /><span className="relative rounded-full bg-background/80 px-2 py-1 text-[10px] font-medium text-foreground">{project.status}</span></div><div className="p-4"><h3 className="font-semibold">{project.name}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-muted-foreground">{project.description}</p><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>{project.updatedAt}</span><button className="flex items-center gap-1 font-medium text-foreground hover:text-primary"><Play className="size-3" />Open</button></div><div className="mt-3 h-1 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${project.progress}%` }} /></div></div></article> }
