'use client'

import { useMemo, useState } from 'react'
import { FileAudio, ImageIcon, Search, Star, ShieldAlert, ExternalLink } from 'lucide-react'
import type { RegistryAsset } from '@/lib/data/asset-registry'

export function AssetLibrary({ assets }: { assets: RegistryAsset[] }) {
  const [query, setQuery] = useState('')
  const [kind, setKind] = useState('all')
  const [sort, setSort] = useState<'recent' | 'name'>('recent')
  const [showFavorites, setShowFavorites] = useState(false)
  const [favorites, setFavorites] = useState<Set<string>>(new Set())
  const [reported, setReported] = useState<string | null>(null)
  const filtered = useMemo(() => assets.filter((asset) => {
    const matchesQuery = !query || `${asset.name} ${(asset.tags ?? []).join(' ')}`.toLowerCase().includes(query.toLowerCase())
    return matchesQuery && (kind === 'all' || asset.kind === kind) && (!showFavorites || favorites.has(asset.id))
  }).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : 0), [assets, favorites, kind, query, showFavorites, sort])
  const toggleFavorite = async (id: string) => { const favorite = !favorites.has(id); setFavorites((current) => { const next = new Set(current); if (favorite) { next.add(id) } else { next.delete(id) }; return next }); await fetch(`/api/assets/${id}/favorite`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ favorite }) }) }
  return <div className="max-w-6xl">
    <div className="flex flex-col gap-4 border-b border-border pb-6 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Asset registry</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Find the building blocks</h1><p className="mt-2 max-w-xl text-muted-foreground">Reusable sprites, sounds, and generated media for your game projects.</p></div><div className="flex items-center gap-2 text-sm text-muted-foreground"><span className="font-semibold text-foreground">{assets.length}</span> registered assets</div></div>
    <div className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search assets</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name or tag" className="h-11 w-full rounded-xl border border-border bg-card pl-9 pr-3 text-sm outline-none ring-primary/30 focus:ring-2" /></label><select value={kind} onChange={(event) => setKind(event.target.value)} aria-label="Filter asset type" className="h-11 rounded-xl border border-border bg-card px-3 text-sm"><option value="all">All types</option><option value="image">Images</option><option value="sprite">Sprites</option><option value="audio">Audio</option></select><select value={sort} onChange={(event) => setSort(event.target.value as 'recent' | 'name')} aria-label="Sort assets" className="h-11 rounded-xl border border-border bg-card px-3 text-sm"><option value="recent">Recent</option><option value="name">Name</option></select><button type="button" onClick={() => setShowFavorites((value) => !value)} aria-pressed={showFavorites} className={`h-11 rounded-xl border px-3 text-sm ${showFavorites ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-card text-muted-foreground'}`}>Favorites</button></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((asset) => <article key={asset.id} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex aspect-[4/3] items-center justify-center bg-secondary/50">{asset.kind === 'audio' ? <FileAudio className="size-10 text-primary" /> : <ImageIcon className="size-10 text-primary" />}</div><div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{asset.name}</h2><p className="mt-1 text-xs uppercase tracking-wider text-muted-foreground">{asset.kind} · {asset.source_type}</p></div><button type="button" onClick={() => toggleFavorite(asset.id)} aria-label={`Favorite ${asset.name}`} className="rounded-lg p-2 text-muted-foreground hover:bg-secondary hover:text-primary"><Star className={`size-4 ${favorites.has(asset.id) ? 'fill-current text-primary' : ''}`} /></button></div><div className="flex flex-wrap gap-1.5">{(asset.tags ?? []).slice(0, 4).map((tag) => <span key={tag} className="rounded-full bg-secondary px-2 py-1 text-xs text-muted-foreground">{tag}</span>)}</div><div className="flex items-center justify-between border-t border-border pt-3 text-xs text-muted-foreground"><span>{asset.license ?? 'License not set'}</span><div className="flex items-center gap-1"><button type="button" onClick={() => setReported(asset.id)} aria-label={`Report ${asset.name}`} className="rounded-md p-1.5 hover:bg-secondary hover:text-foreground"><ShieldAlert className="size-3.5" /></button>{asset.source_url && <a href={asset.source_url} target="_blank" rel="noreferrer" aria-label={`Open source for ${asset.name}`} className="rounded-md p-1.5 hover:bg-secondary hover:text-foreground"><ExternalLink className="size-3.5" /></a>}</div></div>{reported === asset.id && <p className="text-xs text-primary">Thanks — this asset is queued for review.</p>}</div></article>)} </div>{filtered.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No assets match those filters.</div>}</div>
}
