import Link from 'next/link'
import { redirect } from 'next/navigation'
import { ArrowLeft, FolderPlus } from 'lucide-react'
import { getCurrentUser, listProjects } from '@/lib/data/game-lab'
import { GAME_GENRES } from '@/lib/data/game-lab-types'
import { ProjectForm } from '@/components/projects/project-form'

export default async function ProjectsPage() {
  const user = await getCurrentUser(); if (!user) redirect('/auth/sign-in')
  const projects = await listProjects()
  return <main className="min-h-screen px-5 py-8 md:px-10"><div className="mx-auto max-w-6xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Dashboard</Link><header className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Build / Projects</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Your game projects</h1><p className="mt-2 max-w-xl text-muted-foreground">Open a project to edit its foundation, manage assets, and prepare the workspace for future game systems.</p></div><details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground"><FolderPlus className="size-4" />New project</summary><div className="absolute right-0 z-10 mt-3 w-[min(24rem,calc(100vw-2.5rem))] rounded-2xl border border-border bg-card p-5 shadow-xl"><h2 className="mb-4 text-lg font-semibold">Start a new game</h2><ProjectForm /></div></details></header>{projects.length === 0 ? <section className="mt-12 rounded-3xl border border-dashed border-border bg-card/60 p-10 text-center"><h2 className="text-xl font-semibold">Your workspace is ready.</h2><p className="mx-auto mt-2 max-w-md text-muted-foreground">Create your first 2D game project to start shaping its foundation.</p></section> : <section className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <Link key={project.id} href={`/dashboard/projects/${project.id}`} className="group rounded-2xl border border-border bg-card p-6 transition-colors hover:border-primary/60"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-secondary px-3 py-1 text-xs text-secondary-foreground">{project.genre ?? 'Genre pending'}</span><span className="text-xs text-muted-foreground">{project.status}</span></div><h2 className="mt-8 text-xl font-semibold group-hover:text-primary">{project.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{project.description ?? 'No description yet.'}</p><p className="mt-6 text-xs text-muted-foreground">Updated {new Date(project.updated_at).toLocaleDateString()}</p></Link>)}</section>}<div className="mt-8 flex flex-wrap gap-2">{GAME_GENRES.map((genre) => <span key={genre} className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">{genre}</span>)}</div></div></main>
}
