'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { ASSET_BUCKET, type GameAsset } from '@/lib/data/asset-types'
export function AssetManager({ projectId, initialAssets }: { projectId: string; initialAssets: GameAsset[] }) { const router = useRouter(); const [assets, setAssets] = useState(initialAssets); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [urls, setUrls] = useState<Record<string,string>>({})
  async function loadUrl(asset: GameAsset) { if (urls[asset.id]) return; const { data } = await createClient().storage.from(ASSET_BUCKET).createSignedUrl(asset.storage_path, 3600); if (data?.signedUrl) setUrls((v) => ({ ...v, [asset.id]: data.signedUrl })) }
  async function upload(form: HTMLFormElement) { const file = (form.elements.namedItem('file') as HTMLInputElement).files?.[0]; if (!file) return; setBusy(true); setMessage(''); const body = new FormData(form); const res = await fetch(`/api/projects/${projectId}/assets`, { method: 'POST', body }); if (!res.ok) { setMessage((await res.json()).error ?? 'Upload failed.'); setBusy(false); return } setAssets([await res.json(), ...assets]); form.reset(); setBusy(false); setMessage('Asset uploaded.'); router.refresh() }
  async function remove(asset: GameAsset) { if (!confirm(`Delete ${asset.name}?`)) return; const res = await fetch(`/api/assets/${asset.id}`, { method: 'DELETE' }); if (res.ok) setAssets(assets.filter((item) => item.id !== asset.id)); else setMessage('Could not delete asset.') }
  return <section className="mt-8 rounded-2xl border border-border bg-card p-6"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">Asset library</p><h2 className="mt-2 text-2xl font-semibold">Images, sprites, and audio</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Keep creative files inside Game Lab. Uploads are private and scoped to this project.</p></div><form className="flex flex-col gap-2 md:flex-row" onSubmit={(e) => { e.preventDefault(); upload(e.currentTarget) }}><input name="file" type="file" accept="image/png,image/jpeg,image/webp,image/gif,audio/mpeg,audio/wav,audio/ogg" required className="max-w-full text-sm" /><button disabled={busy} className="h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-60">{busy ? 'Uploading…' : 'Upload asset'}</button></form></div>{message && <p role="status" className="mt-4 text-sm text-muted-foreground">{message}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{assets.map((asset) => <article key={asset.id} className="overflow-hidden rounded-xl border border-border bg-background"><div className="flex h-36 items-center justify-center bg-muted/30">{asset.asset_type === 'audio' ? <audio controls src={urls[asset.id]} onPlay={() => loadUrl(asset)} className="w-[90%]" /> : urls[asset.id] ? <img src={urls[asset.id]} alt={asset.name} className="h-full w-full object-contain" /> : <button onClick={() => loadUrl(asset)} className="text-sm text-primary">Preview image</button>}</div><div className="flex items-start justify-between gap-3 p-4"><div className="min-w-0"><h3 className="truncate font-semibold">{asset.name}</h3><p className="mt-1 text-xs uppercase tracking-wider text-muted-foreground">{asset.asset_type} · {(asset.size_bytes / 1024 / 1024).toFixed(1)} MB</p>{asset.description && <p className="mt-2 text-sm text-muted-foreground">{asset.description}</p>}</div><button onClick={() => remove(asset)} className="text-xs text-destructive">Delete</button></div></article>)}</div>{assets.length === 0 && <p className="mt-8 text-sm text-muted-foreground">No assets yet. Upload the first image, sprite, or audio file.</p>}</section> }
