'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Box, ChevronDown, ChevronRight, Eye, EyeOff, Maximize2, Pause, Play, RotateCcw, Save, Search, Square, Wrench, X } from 'lucide-react'
import { GameCanvas } from '@/components/runtime/game-canvas'
import type { GameProject } from '@/lib/data/game-lab-types'
import { projectToGameDefinition } from '@/lib/runtime/project-definition'

type Panel = 'scene' | 'inspector' | 'tools' | null
type Entity = ReturnType<typeof projectToGameDefinition>['scenes'][number]['entities'][number]

export function ProjectWorkspaceEditor({ project }: { project: GameProject }) {
  const definition = useMemo(() => projectToGameDefinition(project), [project])
  const [sceneId, setSceneId] = useState(definition.metadata.startingSceneId ?? definition.scenes[0]?.id ?? '')
  const [selectedId, setSelectedId] = useState(definition.scenes[0]?.entities[0]?.id ?? '')
  const [mobilePanel, setMobilePanel] = useState<Panel>(null)
  const [mode, setMode] = useState<'edit' | 'play'>('edit')
  const [visible, setVisible] = useState<Record<string, boolean>>({})
  const scene = definition.scenes.find((item) => item.id === sceneId) ?? definition.scenes[0]
  const selected = scene?.entities.find((item) => item.id === selectedId) ?? scene?.entities[0]
  const setScene = (id: string) => { setSceneId(id); const next = definition.scenes.find((item) => item.id === id); setSelectedId(next?.entities[0]?.id ?? '') }
  const isVisible = (entity: Entity) => visible[entity.id] !== false

  const hierarchy = <div className="flex min-h-0 flex-col gap-3">
    <div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Hierarchy</span><span className="font-mono text-[10px] text-muted-foreground">{scene?.entities.length ?? 0}</span></div>
    <label className="flex items-center gap-2 rounded-md border border-border bg-background px-2.5 py-2 text-xs text-muted-foreground"><Search className="size-3.5" /><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Filter objects" aria-label="Filter objects" /></label>
    <div className="flex items-center gap-1 text-xs font-medium"><ChevronDown className="size-3.5 text-muted-foreground" />{scene?.name ?? 'Scene'}</div>
    <div className="flex min-h-0 flex-col gap-1 overflow-auto pl-3">{scene?.entities.map((entity) => <button key={entity.id} onClick={() => { setSelectedId(entity.id); setMobilePanel(null) }} className={`flex items-center gap-2 rounded-md px-2.5 py-2 text-left text-xs ${selected?.id === entity.id ? 'bg-primary/15 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><ChevronRight className="size-3 text-muted-foreground" /><Box className="size-3.5" /><span className="min-w-0 flex-1 truncate">{entity.name}</span>{!isVisible(entity) && <EyeOff className="size-3" />}</button>)}</div>
  </div>

  const inspector = <div className="flex min-h-0 flex-col gap-4"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Inspector</span>{selected && <span className="font-mono text-[10px] text-primary">{Object.keys(selected.components)[0] ?? 'object'}</span>}</div>{selected ? <><div><h2 className="truncate text-sm font-semibold">{selected.name}</h2><p className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{selected.id}</p></div><InspectorSection label="Transform"><div className="grid grid-cols-2 gap-2">{[['X', selected.components.transform.position.x], ['Y', selected.components.transform.position.y], ['W', (selected.components.collider as { size?: { x: number; y: number } } | undefined)?.size?.x ?? 0], ['H', (selected.components.collider as { size?: { x: number; y: number } } | undefined)?.size?.y ?? 0]].map(([label, value]) => <div key={label} className="rounded-md border border-border bg-background px-2.5 py-2"><p className="font-mono text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-xs">{value}</p></div>)}</div></InspectorSection><InspectorSection label="Components"><div className="flex flex-wrap gap-1.5">{Object.keys(selected.components).map((component) => <span key={component} className="rounded border border-border px-2 py-1 font-mono text-[10px] text-muted-foreground">{component}</span>)}</div></InspectorSection><div className="flex gap-2"><button className="flex flex-1 items-center justify-center gap-2 rounded-md border border-border px-2 py-2 text-xs hover:bg-muted" onClick={() => setVisible({ ...visible, [selected.id]: !isVisible(selected) })}>{isVisible(selected) ? <Eye className="size-3.5" /> : <EyeOff className="size-3.5" />}Visible</button><Link href={`/projects/${project.id}/customize`} className="flex flex-1 items-center justify-center gap-2 rounded-md bg-primary px-2 py-2 text-xs font-medium text-primary-foreground"><Wrench className="size-3.5" />Customize</Link></div> </> : <p className="text-xs text-muted-foreground">Select an object in the hierarchy.</p>}</div>

  return <div className="flex min-h-[calc(100vh-10rem)] flex-col gap-3">
    <header className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3"><div className="flex min-w-0 items-center gap-2"><span className="rounded border border-primary/30 bg-primary/10 px-2 py-1 font-mono text-[10px] uppercase tracking-wider text-primary">Workspace</span><span className="text-muted-foreground">/</span><select value={scene?.id} onChange={(event) => setScene(event.target.value)} className="max-w-40 truncate bg-transparent text-sm font-medium outline-none"><option value={scene?.id}>{scene?.name ?? 'Scene'}</option>{definition.scenes.filter((item) => item.id !== scene?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="flex items-center gap-1.5"><div className="flex rounded-md border border-border bg-card p-0.5"><button onClick={() => setMode('edit')} className={`rounded px-2.5 py-1.5 text-xs ${mode === 'edit' ? 'bg-secondary text-foreground' : 'text-muted-foreground'}`}>Edit</button><button onClick={() => setMode('play')} className={`rounded px-2.5 py-1.5 text-xs ${mode === 'play' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>Play</button></div><button className="rounded-md border border-border p-2 text-muted-foreground hover:text-foreground" aria-label="Save draft"><Save className="size-3.5" /></button><Link href={`/play/${project.id}`} className="inline-flex items-center gap-1.5 rounded-md bg-primary px-2.5 py-2 text-xs font-medium text-primary-foreground"><Play className="size-3.5" />Preview</Link></div></header>
    <div className="flex items-center justify-between gap-2 rounded-md border border-border bg-card px-2 py-1.5"><div className="flex items-center gap-1"><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Select tool"><Wrench className="size-3.5" /></button><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Move tool">↕</button><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Rotate tool">↻</button></div><span className="font-mono text-[10px] text-muted-foreground">{mode === 'play' ? 'PLAYING' : 'EDITING'} · {scene?.name ?? 'Scene'}</span><div className="flex items-center gap-1"><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Pause preview"><Pause className="size-3.5" /></button><button onClick={() => setMode('edit')} className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Stop preview"><Square className="size-3.5" /></button><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Restart preview"><RotateCcw className="size-3.5" /></button><button className="rounded p-1.5 text-muted-foreground hover:bg-muted" aria-label="Fullscreen preview"><Maximize2 className="size-3.5" /></button></div></div>
    <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[210px_minmax(0,1fr)_230px]"><aside className="hidden min-h-0 rounded-md border border-border bg-card p-3 lg:block">{hierarchy}</aside><section className="flex min-h-[420px] min-w-0 flex-col rounded-md border border-border bg-card p-2"><div className="flex items-center justify-between border-b border-border px-2 pb-2"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary" /><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Game view</span></div><span className="font-mono text-[10px] text-muted-foreground">{definition.settings.viewport.width} × {definition.settings.viewport.height}</span></div><div className="relative mt-2 min-h-0 flex-1 overflow-hidden rounded border border-border bg-muted"><GameCanvas definition={definition} /></div><div className="flex items-center justify-between px-2 pt-2 font-mono text-[10px] text-muted-foreground"><span>{mode === 'play' ? 'Runtime active' : 'Scene preview'}</span><span>{scene?.entities.length ?? 0} objects</span></div></section><aside className="hidden min-h-0 rounded-md border border-border bg-card p-3 lg:block">{inspector}</aside></div>
    <div className="grid grid-cols-3 gap-2 lg:hidden"><button onClick={() => setMobilePanel('scene')} className="rounded-md border border-border bg-card px-3 py-2.5 text-xs">Scene</button><button onClick={() => setMobilePanel('inspector')} className="rounded-md border border-border bg-card px-3 py-2.5 text-xs">Inspect</button><button onClick={() => setMobilePanel('tools')} className="rounded-md border border-border bg-card px-3 py-2.5 text-xs">Tools</button></div>
    {mobilePanel && <div className="fixed inset-x-0 bottom-0 z-20 max-h-[72vh] overflow-auto rounded-t-xl border border-border bg-card p-4 shadow-2xl lg:hidden"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{mobilePanel === 'scene' ? 'Scene hierarchy' : mobilePanel === 'inspector' ? 'Inspector' : 'Tools'}</span><button onClick={() => setMobilePanel(null)} aria-label="Close panel"><X className="size-4" /></button></div>{mobilePanel === 'scene' ? hierarchy : mobilePanel === 'inspector' ? inspector : <div className="grid grid-cols-2 gap-2"><button className="rounded-md border border-border p-3 text-xs">Select</button><button className="rounded-md border border-border p-3 text-xs">Move</button><button className="rounded-md border border-border p-3 text-xs">Rotate</button><button className="rounded-md border border-border p-3 text-xs">Scale</button></div>}</div>}
  </div>
}

function InspectorSection({ label, children }: { label: string; children: React.ReactNode }) { return <section className="border-t border-border pt-3"><p className="mb-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>{children}</section> }
