'use client'

import { useState } from 'react'
import type { GameProject } from '@/lib/data/game-lab-types'
import type { GameProjectVersion } from '@/lib/data/game-lab'

export function ProjectVersionsPanel({ project, versions }: { project: GameProject; versions: GameProjectVersion[] }) {
  const [rows, setRows] = useState(versions); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  async function act(action: 'publish' | 'restore', versionId?: string) { setBusy(true); setMessage(''); const response = await fetch(`/api/projects/${project.id}/versions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, versionId }) }); const data = await response.json(); if (!response.ok) setMessage(data.errors?.join(', ') || data.error || 'Unable to update version'); else { setMessage(action === 'publish' ? 'Draft published.' : 'Version restored to Draft.'); if (data.version) setRows((current) => [data.version, ...current]) } setBusy(false) }
  return <section className="max-w-3xl space-y-6"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Release control</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Versions</h2><p className="mt-2 text-muted-foreground">Every publish creates an immutable snapshot. Editing always returns to Draft.</p></div><div className="flex items-center justify-between rounded-xl border border-border bg-card p-4"><div><p className="font-medium">Current status</p><p className="text-sm text-muted-foreground">{project.status === 'published' ? 'Published build is live.' : 'Draft changes are private.'}</p></div><button disabled={busy} onClick={() => act('publish')} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy ? 'Saving…' : 'Publish Draft'}</button></div>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}<div className="space-y-3">{rows.length === 0 ? <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No published versions yet.</div> : rows.map((version) => <div key={version.id} className="flex items-center justify-between gap-4 rounded-xl border border-border bg-card p-4"><div><p className="font-medium">{version.label || `Version ${version.version_number}`}</p><p className="text-xs text-muted-foreground">Created {new Date(version.created_at).toLocaleString()}</p></div><button disabled={busy} onClick={() => act('restore', version.id)} className="rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-muted disabled:opacity-50">Restore Draft</button></div>)}</div></section>
}
