'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { GAME_GENRES, type GameGenre, type GameProject } from '@/lib/data/game-lab-types'
import { deleteProject, updateProject } from '@/lib/data/projects-client'

export function ProjectDetail({ project }: { project: GameProject }) {
  const router = useRouter(); const [name, setName] = useState(project.name); const [description, setDescription] = useState(project.description ?? ''); const [genre, setGenre] = useState<GameGenre>(project.genre ?? 'Platformer'); const [status, setStatus] = useState(project.status); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); try { await updateProject(project.id, { name, description, genre, status }); setMessage('Changes saved.'); router.refresh() } catch { setMessage('Could not save changes.') } finally { setSaving(false) } }
  async function remove() { if (!window.confirm(`Delete ${project.name}? This cannot be undone.`)) return; await deleteProject(project.id); router.push('/dashboard/projects'); router.refresh() }
  const sections = Object.keys(project.foundation ?? {})
  return <div className="grid gap-8 lg:grid-cols-[1.3fr_0.7fr]"><form onSubmit={save} className="flex flex-col gap-5 rounded-2xl border border-border bg-card p-6"><label className="flex flex-col gap-2 text-sm font-medium">Project name<input value={name} onChange={(e) => setName(e.target.value)} className="h-11 rounded-xl border border-input bg-background px-3" /></label><label className="flex flex-col gap-2 text-sm font-medium">Genre<select value={genre} onChange={(e) => setGenre(e.target.value as GameGenre)} className="h-11 rounded-xl border border-input bg-background px-3">{GAME_GENRES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex flex-col gap-2 text-sm font-medium">Description<textarea rows={4} value={description} onChange={(e) => setDescription(e.target.value)} className="resize-none rounded-xl border border-input bg-background px-3 py-3" /></label><label className="flex flex-col gap-2 text-sm font-medium">Status<select value={status} onChange={(e) => setStatus(e.target.value as GameProject['status'])} className="h-11 rounded-xl border border-input bg-background px-3"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label>{message && <p className="text-sm text-muted-foreground" role="status">{message}</p>}<button disabled={saving} className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground disabled:opacity-60">{saving ? 'Saving…' : 'Save changes'}</button></form><aside className="flex flex-col gap-4"><div className="rounded-2xl border border-border bg-card p-6"><p className="font-mono text-xs uppercase tracking-[0.16em] text-primary">Foundation</p><h2 className="mt-2 text-xl font-semibold">Game structure</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Modular slots ready for the future editor.</p><div className="mt-6 grid grid-cols-2 gap-2">{sections.map((section) => <div key={section} className="rounded-xl bg-secondary px-3 py-3 text-sm capitalize text-secondary-foreground">{section}<span className="mt-1 block text-xs text-muted-foreground">Empty</span></div>)}</div></div><button type="button" onClick={remove} className="rounded-xl border border-destructive/40 px-4 py-3 text-sm font-medium text-destructive hover:bg-destructive/10">Delete project</button></aside></div>
}
